### ISSUE TITLE
Convert Game Simulator into Node

### ISSUE THREAD

**Issue by szgula** [szgula/UofG_Robotics_TDP#12]
DoD:
Convert Game Simulator into Node and add relevant communication

#7 #11  needed to be finished first

**Comment by szgula** [comment]
@OmarJabri7  the code I worked today in on branch linked below, take a look in a free moment ;) 
`https://github.com/szgula/UofG_Robotics_TDP/tree/dev/szgula/ros_issue_8_and_12`

**Comment by OmarJabri7** [comment]
Already did ! Will follow same format to create controller node. @szgula
