### ISSUE TITLE
Issues of the speed of ball 

### ISSUE THREAD

**Issue by Yifan-Xie** [szgula/UofG_Robotics_TDP#31]
- [x] The speed of the ball is too fast so that the robot can't catch the ball
- [x] The ball needs to take a long period of time to stop.

**Comment by yonMaor** [comment]
Hi, is there more information on this issue?

**Comment by szgula** [comment]
@Yifan-Xie take a look here:
1) This parameter sets how much energy is preserved after the ball bounced from the wall 
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L62
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L132
2) Friction - is proportional to rate of change in ball's velocity (you can increase it)
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L60
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L76
3) You can control the velocity after the "Kick" action in 2 ways: with max ball velocity threshold or by kick velocity:
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L57
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L246
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L259
4) You can add minimum velocity of the ball, this has many benefits: has similar effect to static friction, makes computation more efficient etc
Start for example here:
https://github.com/szgula/UofG_Robotics_TDP/blob/8be76edf9efd91b736e5d0ab8718623e178779d1/GameEngine/ball_model.py#L75
and do sth like:
`If abs(vel) < min_vel_threshold: vel = 0`

I hope it helps :)
